### ISSUE TITLE
Push notification not received when app is closed in android

### ISSUE THREAD

**Issue by dipti-samyak** [ConnectyCube/connectycube-reactnative-samples#260] opened 2021-08-12 18:09 UTC
Hello,
I am facing an issue with push notification in android app. Push notification not received when app is closed. It is working well when app is in background.

Can anyone please help me with this issue?

Thank you in advance.

**Comment by ccvlad** [comment] 2021-08-16 07:27
Hello, @dipti-samyak !

- Could you specify - is it Android/iOS, phone's model?
- Show your `someProject/android/app/src/main/AndroidManifest.xml` file if it's Android OS.
- What method do you use to get data for notification?
- Which method you call to display the notification?

Would be helpful if you show logs where are you getting push notification in background mode.

**Comment by dipti-samyak** [comment] 2021-08-16 11:04
``Hello @ccvlad 

- This issue is for android device
- Notification is not coming in any of the android device when application is closed
- I am using onNotification method to get data for notification
- Below is the AndroidManifest.xml file content: 
`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.kosm">
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

	<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
	<uses-permission android:name="android.permission.VIBRATE" />
	
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
	<uses-permission android:name="android.permission.WRITE_CONTACTS" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-feature android:name="android.hardware.camera" />
	<uses-feature android:name="android.hardware.camera.autofocus" />
	<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<application android:name=".MainApplication" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:requestLegacyExternalStorage="true" android:largeHeap="true" android:networkSecurityConfig="@xml/network_security_config" android:roundIcon="@mipmap/ic_launcher_round" android:theme="@style/AppTheme">
		<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />

		<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name" />
		<activity android:name="com.facebook.CustomTabActivity" android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="@string/fb_login_protocol_scheme" />
			</intent-filter>
		</activity>
		<activity android:name=".MainActivity" 
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize" 
			android:label="@string/app_name" 
			android:windowSoftInputMode="adjustResize"
			android:launchMode="singleTop">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.DOWNLOAD_COMPLETE" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
		<meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value="gcm" />
		<meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="gcm" />
		
		
		<meta-data android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@android:color/white" />
		<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
		<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
			<intent-filter>
				<action android:name="android.intent.action.BOOT_COMPLETED" />
			</intent-filter>
		</receiver>
		<service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" />
		
		<service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm" android:exported="false">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
			</intent-filter>
		</service>
		
		
		<service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService" android:exported="false">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
			</intent-filter>
		</service>
		


		<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
		
		
		<service android:name="com.connectycube.pushnotifications.services.fcm.FcmPushListenerService">
   				<intent-filter>
       				<action android:name="com.google.firebase.MESSAGING_EVENT" />
   				</intent-filter>
		</service>
		<service android:name="com.connectycube.pushnotifications.services.fcm.FcmPushInstanceIDService">
   			<intent-filter>
       			<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
  			</intent-filter>
		</service>
        
	</application>
</manifest>
`

**Comment by ccvlad** [comment] 2021-08-17 10:24
> Note that we are using local notification for getting notification in android.

You can't display localNotification if app is closed. You should configure and use push notification.

Are you using [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) or [react-native-firebase](https://rnfirebase.io/messaging/usage)? Refer to guide one of those libs

Check our docs - https://developers.connectycube.com/reactnative/push-notifications
Our sample RNchat with push notification - https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat

**Comment by UmerQur3shi** [comment] 2021-11-11 13:05
@ccvlad I'm having the same issue and I'm using react-native-push-notification, everything is configured according to your docs and the code is same as you provided in the example. When the App is open I get silent data as notification, no popup no sound, I had to create a localNotification in my onNotification method to display it. And when the app is killed, I don't get any notification.

**Comment by NIDHINgl** [comment] 2022-03-14 15:17
@ccvlad, we are also facing the same issue, I followed the same code base and document but the notification is not receiving, Notification received only if trigger local. 

> > Note that we are using local notification for getting notification in android.
> 
> You can't display localNotification if app is closed. You should configure and use push notification.
> 
> Are you using [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) or [react-native-firebase](https://rnfirebase.io/messaging/usage)? Refer to guide one of those libs
> 
> Check our docs - https://developers.connectycube.com/reactnative/push-notifications Our sample RNchat with push notification - https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat

**Comment by andybui090** [comment] 2022-04-22 04:56
I have checked code, with new firebase version, please help remove priority: "high" and contentAvailable from backend if has any to work android, I think this issues related with that

**Comment by DaveLomber** [comment] 2022-05-03 13:11
@dipti-samyak @andybui090 @UmerQur3shi @NIDHINgl 

guys, the issue is addressed in new MR https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296

Please read the details and provide a feedback/comments if any

**Closed** 2022-05-13 08:23 UTC
