### ISSUE TITLE
Can not receive remote notifications

### ISSUE THREAD

**Issue by abdoerrahiem** [ConnectyCube/connectycube-reactnative-samples#266] opened 2021-08-28 05:56 UTC
In my project I have to use local notification to show notifications, because I can't receive from remote notifications. But it doesn't work when the app is killed. Why can't I receive remote notifications?

**Comment by abdoerrahiem** [comment] 2021-08-28 06:05
This is my AndroidManifest.xml
https://shrib.com/#YellowCrownedNightHeron6yMYXEy

**Comment by DaveLomber** [comment] 2021-08-30 07:43
Hi @abdoerrahiem 

did you follow the https://developers.connectycube.com/reactnative/push-notifications guide?

**Comment by abdoerrahiem** [comment] 2021-08-30 09:04
> Hi @abdoerrahiem
> 
> did you follow the https://developers.connectycube.com/reactnative/push-notifications guide?

Yeah I did

**Comment by abdoerrahiem** [comment] 2021-08-30 09:06
It was successful... When I send push notification from admin panel it just appears on the console.

**Comment by DaveLomber** [comment] 2021-08-31 07:28
So it works well now?

**Comment by abdoerrahiem** [comment] 2021-08-31 08:12
> So it works well now?

No.. I can't receive remote notification as before

**Comment by DaveLomber** [comment] 2021-09-02 06:13
Do you use Expo or RN CLI?

Let's sumamrize:

1 - you have subscribed to push notifications via API
2 - now you send a push from admin panel - what status you receive? There is a file you can download and see the response 
3 - but pushes do not come on device

correct?

**Comment by abdoerrahiem** [comment] 2021-09-06 01:38
Yeah correct

**Comment by DaveLomber** [comment] 2021-09-07 06:36
@abdoerrahiem 

I mean 

do you use Expo or RN CLI?

**Comment by abdoerrahiem** [comment] 2021-09-07 06:43
RN CLI

**Comment by UmerQur3shi** [comment] 2021-11-11 12:58
@DaveLomber having the same issue, notifications are received as silent data only, no popup for notification, I create localNotification when the data is received to make it work, but there is nothing I can do to get notifications when the app is killed.

**Comment by NIDHINgl** [comment] 2022-03-01 15:49
@DaveLomber, @TatankaConCube,  I'm also facing the same issue, Notification was not receiving, then I added send notification functionality right after the user send a message, then itself the notification started receiving silently it's not showing alert or badge, I have triggered local notification in OnNotification, but when the app is killed not able to receive a notification. I tried from the admin panel also, status showing as sent but not receiving. I have followed all the steps from the documentation.

**Comment by UmerQur3shi** [comment] 2022-03-01 16:55
> @DaveLomber, @TatankaConCube, I'm also facing the same issue, Notification was not receiving, then I added send notification functionality right after the user send a message, then itself the notification started receiving silently it's not showing alert or badge, I have triggered local notification in OnNotification, but when the app is killed not able to receive a notification. I tried from the admin panel also, status showing as sent but not receiving. I have followed all the steps from the documentation.

There must be some issue with the configuration. Have you successfully registered for push notifications for connectycube? And you have to use local notification to display the silent data as notification popup if the app is active.

**Comment by NIDHINgl** [comment] 2022-03-01 17:08
@UmerQur3shi, I am able to handle when the app is handled, only issue when the app is killed, all the configurations are done based on the documentation

**Comment by UmerQur3shi** [comment] 2022-03-01 17:13
> @UmerQur3shi, I am able to handle when the app is handled, only issue when the app is killed, all the configurations are done based on the documentation

You wrote above that you're sending notifications manually when you send a message, that means it's not configured correctly. The issue is with the configuration, I guess you're not registered for connectycube push notifications. What result you get when you do ConnectyCube.pushnotifications.subscriptions.create(params) ?

**Comment by NIDHINgl** [comment] 2022-03-01 17:16
@UmerQur3shi, You mean from the front-end we don't need to manually send requests it'll handle from connectycube right. ConnectyCube.push notifications.subscriptions.create(params) response is success, i can see the token updated on admin panel

**Comment by UmerQur3shi** [comment] 2022-03-01 17:21
> @UmerQur3shi, You mean from the front-end we don't need to manually send requests it'll handle from connectycube right. ConnectyCube.push notifications.subscriptions.create(params) response is success, i can see the token updated on admin panel

Yes, ConnectyCube sends notification to the receiver automatically. You don't have to code it. Did you add a channel while configuring push notifications?

**Comment by NIDHINgl** [comment] 2022-03-01 17:25
yes

**Comment by UmerQur3shi** [comment] 2022-03-01 17:27
> yes

Idk where you went wrong, for me it's working fine. I tried it with both react native push notifications and react native firebase/messaging.

**Comment by UmerQur3shi** [comment] 2022-03-01 17:44
> ok,
> 
> > > yes
> > 
> > 
> > Idk where you went wrong, for me it's working fine. I tried it with both react native push notifications and react native firebase/messaging.
> 
> ok, we don't need any additional configuration right, the steps those are mentioned in doc is enough right

Yes.

**Comment by NIDHINgl** [comment] 2022-03-13 06:35
@abdoerrahiem did you resolved the issue ?

**Comment by DaveLomber** [comment] 2022-05-03 13:11
@NIDHINgl @UmerQur3shi @abdoerrahiem 

guys, the issue is addressed in new MR https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296

Please read the details and provide a feedback/comments if any

**Closed** 2022-05-13 08:23 UTC
