### ISSUE TITLE
message.sender_id inconsistent type

### ISSUE THREAD

**Issue by ethanx94** [ConnectyCube/connectycube-reactnative-samples#62] opened 2020-04-15 01:56 UTC
Hello,
I'm experiencing an issue running the RNChat sample.
In the chat/index.js file the _renderMessageItem checks to see if the sender id of the message is the same as that of the current user and sets isOtherSender.
However, this check is inconsistent because sometimes the message.sender_id (returned from the historyFromServer) is a string type.
This leads to a few problems causing the Message component to look for an id in the users store that isn't there and ultimately failing when trying to access that user's avatar property (as it is undefined).

I tried to cast the message.sender_id as a Number, but I'm not sure if this is the correct way to do it.

Should I cast to a String or should the sender_id within the constructor of the Message model object be casted to a number in the first place?
<img width="798" alt="Screen Shot 2020-04-14 at 9 32 01 PM" src="https://user-images.githubusercontent.com/4449468/79290600-8b93bd00-7e9a-11ea-8436-f80dcf88856b.png">
<img width="629" alt="Screen Shot 2020-04-14 at 9 55 48 PM" src="https://user-images.githubusercontent.com/4449468/79290659-baaa2e80-7e9a-11ea-9e9f-43036bb3a603.png">

**Comment by Kachanov-dev** [comment] 2020-04-15 11:04
HI @ethanx94.
We get from the server only an integer Sender_id, not a string. It's very strange.
Could you send a logs, please? We can't reproduce it.

**Comment by ethanx94** [comment] 2020-04-15 13:24
You're correct, I misinterpreted what was happening because the messages get added to this.props.history in the Chat component after sending a message. The first place I notice it coming back is in the onMessageListener.
This seems to be reproducible when following steps from #61. That is, I think I am only triggering it when switching accounts and getting duplicated messages.
Two messages get pushed to history, one is a FakeMessage and the other is the real Message object. The real Message object has the string version of sender_id.
And to answer your log question I do get...
`[Response][11] empty body` `cubeInternalUtils.js`
...in my logs when this happens.
<img width="1157" alt="Screen Shot 2020-04-15 at 9 08 44 AM" src="https://user-images.githubusercontent.com/4449468/79341555-ff18e700-7ef9-11ea-88e4-a4a3cdc37741.png">
`this.props.history`
<img width="777" alt="Screen Shot 2020-04-15 at 9 16 57 AM" src="https://user-images.githubusercontent.com/4449468/79341587-0a6c1280-7efa-11ea-8e0f-434fca9c6036.png">

**Comment by Kachanov-dev** [comment] 2020-05-08 09:55
Yes, you can apply an sender_id to a number type.
I am going to close the issue, please re-open if the issue is still persists.

**Closed by Kachanov-dev** 2020-05-08 09:55 UTC
